// app/layout.js (or RootLayout.js, depending on your file structure)
import localFont from "next/font/local";
import "./globals.css";
import Nav from "../app/components/Nav";
import Footer from "../app/components/Footer";
import Loader from "../app/components/Loader"; // Adjust path if necessary
import { AnimatePresence } from "framer-motion";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "sajek-valley",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AnimatePresence>
          {/* Loader will appear on initial load */}
          <Loader />
        </AnimatePresence>

        {/* Render the Nav component at the top */}
        <Nav />

        {/* Main content area */}
        <main>{children}</main>

        {/* Render the Footer component at the bottom */}
        <Footer />
      </body>
    </html>
  );
}
