import localFont from "next/font/local";
import "./globals.css";
import Nav from "../app/components/Nav"; // Adjust the path if necessary
import Footer from "../app/components/Footer"; // Adjust the path if necessary

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render the Nav component at the top */}
        <Nav />
        
        {/* Main content area */}
        <main>{children}</main>
        
        {/* Render the Footer component at the bottom */}
        <Footer />
      </body>
    </html>
  );
}
